
#
# This file is downloaded via the robotpy-sphinx-plugin, and converted
# into a usable sidebar.
#
# This is a downloaded dependency because it's really annoying to make commits
# to all of the projects each time we want to change the sidebar.
#

[projects]
robotpy = "https://robotpy.readthedocs.io"
mostrobotpy = "https://robotpy.readthedocs.io/projects/robotpy"
commandv2 = "https://robotpy.readthedocs.io/projects/commands-v2"
phoenix5 = "https://robotpy.readthedocs.io/projects/ctre"
phoenix6 = "https://api.ctr-electronics.com/phoenix6/release/python"
navx = "https://robotpy.readthedocs.io/projects/navx"
pathplannerlib = "https://mjansen4857.com/pathplanner/docs/python"
photonvision = "https://robotpy.readthedocs.io/projects/photonvision"
pwfusion = "https://robotpy.readthedocs.io/projects/pwfusion"
pyfrc = "https://robotpy.readthedocs.io/projects/pyfrc"
pynetworktables = "https://robotpy.readthedocs.io/projects/pynetworktables"
rev = "https://robotpy.readthedocs.io/projects/rev"
rev_color = "https://robotpy.readthedocs.io/projects/rev-color"
romi = "https://robotpy.readthedocs.io/projects/romi"
utilities = "https://robotpy.readthedocs.io/projects/utilities"


[[toctree]]
name = "RobotPy"
items = [
    {p="robotpy", k="Overview", v="index"},
]

[[toctree]]
name = "API Reference"
items = [
    {p="mostrobotpy", k="Most API", v="api"},
    {p="commandv2", k="Commands API", v="api"},
    {p="utilities", k="Utilities API", v="api"},
    {p="pyfrc", k="PyFRC API", v="api"},
]

[[toctree]]
name = "Third Party HW"
items = [
    {p="navx", k="NavX API", v="api"},
    {p="rev", k="REVLib API", v="api"},
    {p="pathplannerlib", k="PathPlannerLib API", v="api"},
    {p="phoenix5", k="Phoenix5 API", v="api"},
    {p="phoenix6", k="Phoenix6 API", v="index"},
    # {p="photonvision", k="PhotonVision API", v="api"},
    {p="pwfusion", k="PWFusion API", v="api"},
]

